### PR TITLE
Add support for heartbeat details.

### PR DESCRIPTION
**Pull request by robholland**
This allows activities to resume where they left off when retring based
on the previously recorded heartbeat details.

### CODE REVIEW

**Review by antstorm — APPROVED** [review]
Looks great, thank you!

**Comment by antstorm** [comment]
@robholland Actually looks like it's failing example specs due to a missing `heartbeat_details` on the test metadata

**Comment by robholland** [comment]
Apologies, forgot to run the examples specs so didn't spot this. Fixed now.

**Review by antstorm — APPROVED** [review]
👍

**Pull request merged**
