### PR TITLE
Require "temporal/version" so Temporal::VERSION can be referenced

### LINKED ISSUE #237: NameError: uninitialized constant Temporal::VERSION
I just updated to the latest SHA and noticed some recent additions for custom search attributes that I wanted to test out.  However, I've run into this exception while trying to call `Temporal.add_custom_search_attributes`.  In my codebase, if I add `require "temporal/version"` in an initializer, everything is good.  Do we need to do that somewhere in the gem?  Should it be required [here](https://github.com/coinbase/temporal-ruby/blob/master/lib/temporal.rb)?  Happy to open a PR if it's helpful!

```
rake aborted!
NameError: uninitialized constant Temporal::VERSION
Did you mean?  REVISION
/opt/app/laddertruck/vendor/bundle/ruby/3.0.0/bundler/gems/temporal-ruby-59ed5911850e/lib/temporal/connection/interceptors/client_name_version_interceptor.rb:8:in `request_response'
/opt/app/laddertruck/vendor/bundle/ruby/3.0.0/gems/grpc-1.38.0/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
/opt/app/laddertruck/vendor/bundle/ruby/3.0.0/gems/grpc-1.38.0/src/ruby/lib/grpc/generic/client_stub.rb:179:in `request_response'
/opt/app/laddertruck/vendor/bundle/ruby/3.0.0/gems/grpc-1.38.0/src/ruby/lib/grpc/generic/service.rb:171:in `block (3 levels) in rpc_stub_class'
/opt/app/laddertruck/vendor/bundle/ruby/3.0.0/bundler/gems/temporal-ruby-59ed5911850e/lib/temporal/connection/grpc.rb:511:in `add_custom_search_attributes'
/opt/app/laddertruck/vendor/bundle/ruby/3.0.0/bundler/gems/temporal-ruby-59ed5911850e/lib/temporal/client.rb:415:in `add_custom_search_attributes'
```

### PR DESCRIPTION
**Pull request by bmorton**
I ran across this after pulling the latest SHA.  This fixes #237 for me when I use this branch.

### CODE REVIEW

**Comment by jeffschoner** [comment]
This is similar to a PR I just created at https://github.com/coinbase/temporal-ruby/pull/241, but I think mine is more correct since it more tightly scopes the require to only where it's strictly needed. What do you think? Does my version also allow you to load?

**Comment by mjameswh** [comment]
I would also go with #241.

**Comment by DeRauk** [comment]
Closing this since it's been fixed with #241

**Comment by DeRauk** [comment]
Closed because it's been fixed with #241

**Pull request closed without merging**
