### PR TITLE
UTF safety

### PR DESCRIPTION
**Pull request by robholland**
Fixes Encoding::UndefinedConversionError errors for some UTF characters.

### CODE REVIEW

**Comment by antstorm** [comment]
@robholland can you help me understand where this error comes from? Is it protobuf encoding complaining or GRCP? Or Temporal server?

**Comment by robholland** [comment]
It's the transcoding attempt that the protobuf code makes to try and turn the serialised JSON string from us (which contains UTF-8 characters which are valid in JSON) into ASCII-8BIT to fit in the `bytes`-typed data field for Temporal Payloads. UTF characters with the high bit set are not transcodable into ASCII-8BIT as they have no ascii equivalent so the transcode fails. Calling `.b` on the serialised JSON string escapes any high-bit-set characters which allows the string to be transcoded to ASCI-8BIT safely, and then deserialised on the other side into the correct UTF-8 characters.

**Comment by robholland** [comment]
Prior art here: https://github.com/protocolbuffers/protobuf/issues/4228

**Review by antstorm — APPROVED** [review]
👍

**Pull request merged**
