### PR TITLE
Support multiple payloads from array input

### PR DESCRIPTION
**Pull request by gvieira**
We have a workflow written in Go that receives two args.

```go
func Workflow(ctx workflow.Context, a string, b string) error {
```

When calling it from a different go program, everything works as expected.

```go
we, err := c.ExecuteWorkflow(context.Background(), workflowOptions, "Workflow", "a.json", "b.json")
```

This is a simple screenshot of the input, from `localhost:8088`.

Screen Shot 2021-03-18 at 20 45 10

However, when calling the very same workflow from Ruby, the current code doesn't work.

```ruby
Temporal.start_workflow('Workflow', 'a.json', 'b.json', options: options)
```

Here's a screenshot of the input in this case:

Screen Shot 2021-03-18 at 20 45 27

We get the following error:

```
wrapError: unable to decode the workflow function input payload with error: payload item 0: unable to decode: json: cannot unmarshal array into Go value of type string
```

... which makes a lot of sense, as it tries to put an array into a string.

-----------

If you dive in and see the code in Go that encodes payloads, you'll end up with something like this:

```go
dataConverter := converter.GetDefaultDataConverter()
input, _ := dataConverter.ToPayloads("a.json", "b.json")
fmt.Println(input.Payloads[0])
fmt.Println(input.Payloads[1])
```

Here, `input` ends up with 2 payloads.

But if you try to do the very same thing in Ruby, you'll get something like this:

```ruby
Temporal::Client::Serializer::Payload.new(['a.json', 'b.json']).to_proto
```

In this case, with the current code, you are going to get a single payload, which encodes the array, hence the wrong input you can see above.

-------

All I've done is to map the array into payloads. I monkey-patched it into the application (for testing purposes) and it worked.

### CODE REVIEW

**Review by antstorm — COMMENTED** [review]
@gvieira thank you for contributing! The code looks good, but can you please explain the reasoning behind this change? Array will already get correctly converted to and from a proto.

A spec exposing this would be useful (the one you've added checks that it results in multiple payloads, but converting it back results in the same array as originally submitted)

**Comment by gvieira** [comment]
Hey @antstorm! Thanks for taking a look at this. I was planning to go through this with a teammate before moving forward and asking for review, but I forgot to set as draft.

Anyway, I've added a description here. I was hoping that [this](https://github.com/coinbase/temporal-ruby/pull/53/files#diff-08901e0e9a9cf55ba6bc099069fd9b962ccab32b5ee707b75c51345cef1e684aR37) spec would help with the understanding of what I was trying to fix.

**Comment by robholland** [comment]
I've added an alternative solution to this which brings the Ruby SDK payload handling in line with the other SDKs and avoids edge cases: https://github.com/coinbase/temporal-ruby/pull/56

**Comment by gvieira** [comment]
Closing in favor of #56.

**Pull request closed without merging**
