### PR TITLE
Require version in client name version interceptor

### PR DESCRIPTION
**Pull request by jeffschoner**
This fixes https://github.com/coinbase/temporal-ruby/issues/237 (an issue with package loading) introduced in #223.

fyi @mjameswh

### CODE REVIEW

**Comment by mjameswh** [comment]
Oops. Not sure how I can have missed this, but that's right.

Regarding the errors in get in CI tests:

```
:search attribute CustomDatetimeField is not defined.
```

In some recent servers (including the Temporal CLI dev server), customer search attributes are no longer present by default. You need to create them yourself.

See this for an example: https://github.com/temporalio/sdk-typescript/blob/main/packages/test/src/helpers.ts#L132

**Comment by mjameswh** [comment]
Oh... there's a cache on server regarding search attributes. That sometime cause a lag (up to 10 seconds) before newly created search attributes are visible to workflow operations.

A very simple solution is to add `
--dynamic-config-value system.forceSearchAttributesCacheRefreshOnRead=true
` add argument to the server.

**Comment by jeffschoner** [comment]
@mjameswh We are using auto-setup, which I think does provision all of these ([source](https://github.com/temporalio/docker-builds/blob/main/docker/auto-setup.sh)). This would also seem to explain why in the Register namespace Github Action step, it mentions all the custom search attributes have been created except for `CustomStringAttribute`. What's odd there is that there's a comment to remove `CustomStringAttribute` eventually. It seems an odd coincidence that attribute would not have been provisioned. Is it possible the docker image contains newer code than what's on master in the link I provided?

Either way, it's not clear to me how to pass that dynamic config flag through to the docker-compose file. Is there an easy way to do this?

There is a sleep step in the Github Actions config that waits for 10s after our set up script runs. It seems like that could also be extended, but `CustomDatetimeField` seems to have been created maybe as much as 45s before it was attempted to be used.

**Review by DeRauk — APPROVED** [review]

**Comment by DeRauk** [comment]
@jeffschoner I'm going to merge this since the test failures aren't related to this change and we need to get this in.

I put out a PR to add the setting @mjameswh mentioned here: https://github.com/coinbase/temporal-ruby/pull/242

Thank you both!

**Pull request merged**
