### PR TITLE
Rename domain -> namespace to match temporal.

### PR DESCRIPTION
**Pull request by robholland**

### CODE REVIEW

**Comment by antstorm** [comment]
@robholland this PR makes sense, but I have some concerns. Mainly this will make cadence <> temporal gems non-syncable, which will make developing both a bit of a nightmare. Can we keep modifications to the client only and use aliases (supporting both `domain` and `namespace`) in all public APIs?

**Review by antstorm — APPROVED** [review]
Also looking good and needs a rebase

**Comment by antstorm** [comment]
@robholland I think this one's ready to go after a rebase

**Comment by robholland** [comment]
Rebased.

**Review by antstorm — APPROVED** [review]

**Pull request merged**
